#cloud-config

ssh_pwauth: false

users:
  - name: debian
    passwd: $6$rounds=4096$9L5WSrOX5xnefydm$0B5ID/erh6/g0W8omTfOPZX7aNWWDIDk8/p6PJBIF5P1/KPasCM2jR6NU97.DdOaa.SvTnbiXwA5KwlfQgnWa.
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcW2jYunchm6gB8eKgYzWnvgLKive8JdQCxj6RyikjugXOgBhgG0os3gxX1Nl0Jyv7evPmbiAxbZReqtZGH0ercdTs12r5mJ7ajVqtELZr7RHW4iBQ5w8CgLIbea8DeO2rGVr0pSMCLTsoecvAwIbIqeDGDF+jpw6CRzRpkyx9oiJ26ww1hAoFL4F/+S0HHOqzCMzac3JvfbRvypcYNgOo5IwT4vxbeoiNUFAS1K7jOQVURsd30TN+NYrdW1IWdeylKS/vBoLtJkWIyJIJvfA24DAHgREb57cFxzTpVmSApKIavJ14YNGSaJf3RywnwB7YWMh6uC4zjVBBsvQseFxLzf89hyn3gtruPBla0vwu3gRRvkrmg2qza0r2GjUU5fRw0OEc7tDW7K8sqq9obKLGeJgNVBLS2cGmxVzgx16k14zX2eT+ApUavJt6hiFUJbeMxYynvCqMXMX5U4FLS+DpogKDF+NS1M6uJEm4Ko4ZDQJ2k1ilNDvSaIHYRIaj7w2PEaCk+1Y0zin1r4mjD+3k0YRtUL0cISFxYLTIHHeMZk1W/QkvMDv9evmlNNW4k1UnGaxyLoStesJaU49gFguLrOHBxT1f1IFq2Go7qTauCd9vtsDQPeCSVpJx2NoCHL1dKfphF8LElY0ogYdXe4JjpL0eWCgiNVKyWSS6GsAVlQ== r@r-XPS-13-9300

runcmd:
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - sudo chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


package_update: true
package_upgrade: true

packages:
  - curl 
  # - docker-ce
  # - docker-ce-cli
  # - containerd.io
  # - docker-buildx-plugin
  # - docker-compose-plugin
  - htop
  - nload
  - sysstat
  - pydf
  - ncdu
  - byobu
  - vim

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

